# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TeraView(object):
    def setupUi(self, TeraView):
        TeraView.setObjectName(_fromUtf8("TeraView"))
        TeraView.resize(1247, 587)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TeraView.sizePolicy().hasHeightForWidth())
        TeraView.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(TeraView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.spectrumCanvas = MatplotlibWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectrumCanvas.sizePolicy().hasHeightForWidth())
        self.spectrumCanvas.setSizePolicy(sizePolicy)
        self.spectrumCanvas.setObjectName(_fromUtf8("spectrumCanvas"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.fileTree = QtGui.QTreeWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTree.sizePolicy().hasHeightForWidth())
        self.fileTree.setSizePolicy(sizePolicy)
        self.fileTree.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.fileTree.setObjectName(_fromUtf8("fileTree"))
        self.verticalLayout.addWidget(self.fileTree)
        self.preferences = QtGui.QStackedWidget(self.layoutWidget)
        self.preferences.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preferences.sizePolicy().hasHeightForWidth())
        self.preferences.setSizePolicy(sizePolicy)
        self.preferences.setObjectName(_fromUtf8("preferences"))
        self.tdmanipulation = QtGui.QWidget()
        self.tdmanipulation.setObjectName(_fromUtf8("tdmanipulation"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tdmanipulation)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tdmanipulation)
        self.groupBox.setEnabled(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dsbTimeShift = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsbTimeShift.setMinimum(-1500.0)
        self.dsbTimeShift.setMaximum(1500.0)
        self.dsbTimeShift.setObjectName(_fromUtf8("dsbTimeShift"))
        self.gridLayout.addWidget(self.dsbTimeShift, 3, 1, 2, 1)
        self.pbApplyTDManipulation = QtGui.QPushButton(self.groupBox)
        self.pbApplyTDManipulation.setObjectName(_fromUtf8("pbApplyTDManipulation"))
        self.gridLayout.addWidget(self.pbApplyTDManipulation, 7, 2, 1, 1)
        self.pbCancelTDManipulation = QtGui.QPushButton(self.groupBox)
        self.pbCancelTDManipulation.setObjectName(_fromUtf8("pbCancelTDManipulation"))
        self.gridLayout.addWidget(self.pbCancelTDManipulation, 7, 0, 1, 1)
        self.pbPreviewTDManipulation = QtGui.QPushButton(self.groupBox)
        self.pbPreviewTDManipulation.setObjectName(_fromUtf8("pbPreviewTDManipulation"))
        self.gridLayout.addWidget(self.pbPreviewTDManipulation, 7, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(654, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 4, 5, 1)
        self.dsbAmplitudeFactor = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsbAmplitudeFactor.setDecimals(6)
        self.dsbAmplitudeFactor.setMinimum(-9999.0)
        self.dsbAmplitudeFactor.setMaximum(9999.0)
        self.dsbAmplitudeFactor.setSingleStep(0.01)
        self.dsbAmplitudeFactor.setProperty("value", 1.0)
        self.dsbAmplitudeFactor.setObjectName(_fromUtf8("dsbAmplitudeFactor"))
        self.gridLayout.addWidget(self.dsbAmplitudeFactor, 2, 1, 1, 1)
        self.cbwhichGraphs = QtGui.QComboBox(self.groupBox)
        self.cbwhichGraphs.setObjectName(_fromUtf8("cbwhichGraphs"))
        self.gridLayout.addWidget(self.cbwhichGraphs, 1, 0, 1, 3)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.rbManipulateCopy = QtGui.QRadioButton(self.groupBox)
        self.rbManipulateCopy.setObjectName(_fromUtf8("rbManipulateCopy"))
        self.gridLayout.addWidget(self.rbManipulateCopy, 5, 1, 1, 1)
        self.rbManipulateReplace = QtGui.QRadioButton(self.groupBox)
        self.rbManipulateReplace.setChecked(True)
        self.rbManipulateReplace.setObjectName(_fromUtf8("rbManipulateReplace"))
        self.gridLayout.addWidget(self.rbManipulateReplace, 5, 0, 1, 1)
        self.leNewName = QtGui.QLineEdit(self.groupBox)
        self.leNewName.setObjectName(_fromUtf8("leNewName"))
        self.gridLayout.addWidget(self.leNewName, 5, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.preferences.addWidget(self.tdmanipulation)
        self.tdcutting = QtGui.QWidget()
        self.tdcutting.setObjectName(_fromUtf8("tdcutting"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tdcutting)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.tdcutting)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(654, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 4, 4, 5, 1)
        self.pbApplyWindowing = QtGui.QPushButton(self.groupBox_2)
        self.pbApplyWindowing.setObjectName(_fromUtf8("pbApplyWindowing"))
        self.gridLayout_2.addWidget(self.pbApplyWindowing, 7, 2, 1, 1)
        self.pbCancelWindowing = QtGui.QPushButton(self.groupBox_2)
        self.pbCancelWindowing.setObjectName(_fromUtf8("pbCancelWindowing"))
        self.gridLayout_2.addWidget(self.pbCancelWindowing, 7, 0, 1, 1)
        self.pbPreviewWindowing = QtGui.QPushButton(self.groupBox_2)
        self.pbPreviewWindowing.setObjectName(_fromUtf8("pbPreviewWindowing"))
        self.gridLayout_2.addWidget(self.pbPreviewWindowing, 7, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.cbwhichGraphs_windowing = QtGui.QComboBox(self.groupBox_2)
        self.cbwhichGraphs_windowing.setObjectName(_fromUtf8("cbwhichGraphs_windowing"))
        self.gridLayout_2.addWidget(self.cbwhichGraphs_windowing, 1, 0, 1, 3)
        self.cbwindowfunction = QtGui.QComboBox(self.groupBox_2)
        self.cbwindowfunction.setObjectName(_fromUtf8("cbwindowfunction"))
        self.cbwindowfunction.addItem(_fromUtf8(""))
        self.cbwindowfunction.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cbwindowfunction, 2, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 3, 2, 1, 1)
        self.rbManipulateReplace_windowing = QtGui.QRadioButton(self.groupBox_2)
        self.rbManipulateReplace_windowing.setChecked(True)
        self.rbManipulateReplace_windowing.setObjectName(_fromUtf8("rbManipulateReplace_windowing"))
        self.gridLayout_2.addWidget(self.rbManipulateReplace_windowing, 5, 0, 1, 1)
        self.rbManipulateCopy_windowing = QtGui.QRadioButton(self.groupBox_2)
        self.rbManipulateCopy_windowing.setObjectName(_fromUtf8("rbManipulateCopy_windowing"))
        self.gridLayout_2.addWidget(self.rbManipulateCopy_windowing, 5, 1, 1, 1)
        self.le_newName_windowing = QtGui.QLineEdit(self.groupBox_2)
        self.le_newName_windowing.setObjectName(_fromUtf8("le_newName_windowing"))
        self.gridLayout_2.addWidget(self.le_newName_windowing, 5, 2, 1, 1)
        self.dsb_risingEdge = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_risingEdge.setObjectName(_fromUtf8("dsb_risingEdge"))
        self.gridLayout_2.addWidget(self.dsb_risingEdge, 3, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.preferences.addWidget(self.tdcutting)
        self.tdzeropadding = QtGui.QWidget()
        self.tdzeropadding.setObjectName(_fromUtf8("tdzeropadding"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tdzeropadding)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.tdzeropadding)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(654, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 4, 4, 5, 1)
        self.pbApplyPadding = QtGui.QPushButton(self.groupBox_3)
        self.pbApplyPadding.setObjectName(_fromUtf8("pbApplyPadding"))
        self.gridLayout_3.addWidget(self.pbApplyPadding, 7, 2, 1, 1)
        self.pbCancelPadding = QtGui.QPushButton(self.groupBox_3)
        self.pbCancelPadding.setObjectName(_fromUtf8("pbCancelPadding"))
        self.gridLayout_3.addWidget(self.pbCancelPadding, 7, 0, 1, 1)
        self.pbPreviewPadding = QtGui.QPushButton(self.groupBox_3)
        self.pbPreviewPadding.setObjectName(_fromUtf8("pbPreviewPadding"))
        self.gridLayout_3.addWidget(self.pbPreviewPadding, 7, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.cbwhichGraphs_zeropadding = QtGui.QComboBox(self.groupBox_3)
        self.cbwhichGraphs_zeropadding.setObjectName(_fromUtf8("cbwhichGraphs_zeropadding"))
        self.gridLayout_3.addWidget(self.cbwhichGraphs_zeropadding, 1, 0, 1, 3)
        self.cbZeroPadding = QtGui.QComboBox(self.groupBox_3)
        self.cbZeroPadding.setObjectName(_fromUtf8("cbZeroPadding"))
        self.cbZeroPadding.addItem(_fromUtf8(""))
        self.cbZeroPadding.addItem(_fromUtf8(""))
        self.cbZeroPadding.addItem(_fromUtf8(""))
        self.cbZeroPadding.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cbZeroPadding, 2, 1, 1, 2)
        self.sbNumberZeros = QtGui.QSpinBox(self.groupBox_3)
        self.sbNumberZeros.setMaximum(9999)
        self.sbNumberZeros.setObjectName(_fromUtf8("sbNumberZeros"))
        self.gridLayout_3.addWidget(self.sbNumberZeros, 3, 1, 1, 1)
        self.rbManipulateReplace_Padding = QtGui.QRadioButton(self.groupBox_3)
        self.rbManipulateReplace_Padding.setChecked(True)
        self.rbManipulateReplace_Padding.setObjectName(_fromUtf8("rbManipulateReplace_Padding"))
        self.gridLayout_3.addWidget(self.rbManipulateReplace_Padding, 5, 0, 1, 1)
        self.rbManipulateCopy_Padding = QtGui.QRadioButton(self.groupBox_3)
        self.rbManipulateCopy_Padding.setObjectName(_fromUtf8("rbManipulateCopy_Padding"))
        self.gridLayout_3.addWidget(self.rbManipulateCopy_Padding, 5, 1, 1, 1)
        self.le_newName_padding = QtGui.QLineEdit(self.groupBox_3)
        self.le_newName_padding.setObjectName(_fromUtf8("le_newName_padding"))
        self.gridLayout_3.addWidget(self.le_newName_padding, 5, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.preferences.addWidget(self.tdzeropadding)
        self.tdinterpolation = QtGui.QWidget()
        self.tdinterpolation.setObjectName(_fromUtf8("tdinterpolation"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tdinterpolation)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.groupBox_4 = QtGui.QGroupBox(self.tdinterpolation)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 2, 2, 1, 1)
        self.dsbinterpolationStep = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dsbinterpolationStep.setDecimals(1)
        self.dsbinterpolationStep.setMinimum(1.0)
        self.dsbinterpolationStep.setProperty("value", 20.0)
        self.dsbinterpolationStep.setObjectName(_fromUtf8("dsbinterpolationStep"))
        self.gridLayout_4.addWidget(self.dsbinterpolationStep, 2, 1, 1, 1)
        self.pbApplyInterpolation = QtGui.QPushButton(self.groupBox_4)
        self.pbApplyInterpolation.setObjectName(_fromUtf8("pbApplyInterpolation"))
        self.gridLayout_4.addWidget(self.pbApplyInterpolation, 6, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(654, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 3, 4, 5, 1)
        self.pbCancelInterpolation = QtGui.QPushButton(self.groupBox_4)
        self.pbCancelInterpolation.setObjectName(_fromUtf8("pbCancelInterpolation"))
        self.gridLayout_4.addWidget(self.pbCancelInterpolation, 6, 0, 1, 1)
        self.pbPreviewInterpolation = QtGui.QPushButton(self.groupBox_4)
        self.pbPreviewInterpolation.setObjectName(_fromUtf8("pbPreviewInterpolation"))
        self.gridLayout_4.addWidget(self.pbPreviewInterpolation, 6, 1, 1, 1)
        self.rbManipulateReplace_interpolation = QtGui.QRadioButton(self.groupBox_4)
        self.rbManipulateReplace_interpolation.setChecked(True)
        self.rbManipulateReplace_interpolation.setObjectName(_fromUtf8("rbManipulateReplace_interpolation"))
        self.gridLayout_4.addWidget(self.rbManipulateReplace_interpolation, 4, 0, 1, 1)
        self.rbManipulateCopy_interpolation = QtGui.QRadioButton(self.groupBox_4)
        self.rbManipulateCopy_interpolation.setObjectName(_fromUtf8("rbManipulateCopy_interpolation"))
        self.gridLayout_4.addWidget(self.rbManipulateCopy_interpolation, 4, 1, 1, 1)
        self.le_newName_interpolation = QtGui.QLineEdit(self.groupBox_4)
        self.le_newName_interpolation.setObjectName(_fromUtf8("le_newName_interpolation"))
        self.gridLayout_4.addWidget(self.le_newName_interpolation, 4, 2, 1, 1)
        self.cbwhichGraphs_interpolation = QtGui.QComboBox(self.groupBox_4)
        self.cbwhichGraphs_interpolation.setObjectName(_fromUtf8("cbwhichGraphs_interpolation"))
        self.cbwhichGraphs_interpolation.addItem(_fromUtf8(""))
        self.cbwhichGraphs_interpolation.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cbwhichGraphs_interpolation, 1, 0, 1, 3)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.groupBox_4)
        self.preferences.addWidget(self.tdinterpolation)
        self.averaging = QtGui.QWidget()
        self.averaging.setObjectName(_fromUtf8("averaging"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.averaging)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.groupBox_7 = QtGui.QGroupBox(self.averaging)
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 3, 0, 1, 1)
        self.pbCancelAveraging = QtGui.QPushButton(self.groupBox_7)
        self.pbCancelAveraging.setObjectName(_fromUtf8("pbCancelAveraging"))
        self.gridLayout_7.addWidget(self.pbCancelAveraging, 5, 0, 1, 1)
        self.pbApplyAveraging = QtGui.QPushButton(self.groupBox_7)
        self.pbApplyAveraging.setObjectName(_fromUtf8("pbApplyAveraging"))
        self.gridLayout_7.addWidget(self.pbApplyAveraging, 5, 2, 1, 1)
        self.pbPreviewAveraging = QtGui.QPushButton(self.groupBox_7)
        self.pbPreviewAveraging.setObjectName(_fromUtf8("pbPreviewAveraging"))
        self.gridLayout_7.addWidget(self.pbPreviewAveraging, 5, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(654, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 1, 4, 6, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_7)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 4, 0, 1, 1)
        self.cbAverageWhere = QtGui.QComboBox(self.groupBox_7)
        self.cbAverageWhere.setObjectName(_fromUtf8("cbAverageWhere"))
        self.cbAverageWhere.addItem(_fromUtf8(""))
        self.cbAverageWhere.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cbAverageWhere, 3, 1, 1, 2)
        self.leNewName_averaging = QtGui.QLineEdit(self.groupBox_7)
        self.leNewName_averaging.setObjectName(_fromUtf8("leNewName_averaging"))
        self.gridLayout_7.addWidget(self.leNewName_averaging, 4, 1, 1, 2)
        self.lwAverage = QtGui.QListWidget(self.groupBox_7)
        self.lwAverage.setObjectName(_fromUtf8("lwAverage"))
        self.gridLayout_7.addWidget(self.lwAverage, 2, 0, 1, 3)
        self.horizontalLayout_9.addWidget(self.groupBox_7)
        self.preferences.addWidget(self.averaging)
        self.fdinterpolation = QtGui.QWidget()
        self.fdinterpolation.setObjectName(_fromUtf8("fdinterpolation"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.fdinterpolation)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupBox_5 = QtGui.QGroupBox(self.fdinterpolation)
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 2, 2, 1, 1)
        self.dsbinterpolationStep_2 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.dsbinterpolationStep_2.setDecimals(1)
        self.dsbinterpolationStep_2.setMinimum(1.0)
        self.dsbinterpolationStep_2.setProperty("value", 20.0)
        self.dsbinterpolationStep_2.setObjectName(_fromUtf8("dsbinterpolationStep_2"))
        self.gridLayout_5.addWidget(self.dsbinterpolationStep_2, 2, 1, 1, 1)
        self.pbApplyInterpolation_2 = QtGui.QPushButton(self.groupBox_5)
        self.pbApplyInterpolation_2.setObjectName(_fromUtf8("pbApplyInterpolation_2"))
        self.gridLayout_5.addWidget(self.pbApplyInterpolation_2, 6, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(654, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 3, 4, 5, 1)
        self.pbCancelInterpolation_2 = QtGui.QPushButton(self.groupBox_5)
        self.pbCancelInterpolation_2.setObjectName(_fromUtf8("pbCancelInterpolation_2"))
        self.gridLayout_5.addWidget(self.pbCancelInterpolation_2, 6, 0, 1, 1)
        self.pbPreviewInterpolation_2 = QtGui.QPushButton(self.groupBox_5)
        self.pbPreviewInterpolation_2.setObjectName(_fromUtf8("pbPreviewInterpolation_2"))
        self.gridLayout_5.addWidget(self.pbPreviewInterpolation_2, 6, 1, 1, 1)
        self.rbManipulateReplace_5 = QtGui.QRadioButton(self.groupBox_5)
        self.rbManipulateReplace_5.setChecked(True)
        self.rbManipulateReplace_5.setObjectName(_fromUtf8("rbManipulateReplace_5"))
        self.gridLayout_5.addWidget(self.rbManipulateReplace_5, 4, 0, 1, 1)
        self.rbManipulateCopy_5 = QtGui.QRadioButton(self.groupBox_5)
        self.rbManipulateCopy_5.setObjectName(_fromUtf8("rbManipulateCopy_5"))
        self.gridLayout_5.addWidget(self.rbManipulateCopy_5, 4, 1, 1, 1)
        self.le_newName_4 = QtGui.QLineEdit(self.groupBox_5)
        self.le_newName_4.setObjectName(_fromUtf8("le_newName_4"))
        self.gridLayout_5.addWidget(self.le_newName_4, 4, 2, 1, 1)
        self.cbwhichGraphs_5 = QtGui.QComboBox(self.groupBox_5)
        self.cbwhichGraphs_5.setObjectName(_fromUtf8("cbwhichGraphs_5"))
        self.cbwhichGraphs_5.addItem(_fromUtf8(""))
        self.cbwhichGraphs_5.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cbwhichGraphs_5, 1, 0, 1, 3)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.preferences.addWidget(self.fdinterpolation)
        self.fdmanipulation = QtGui.QWidget()
        self.fdmanipulation.setObjectName(_fromUtf8("fdmanipulation"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.fdmanipulation)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox_6 = QtGui.QGroupBox(self.fdmanipulation)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.dsbTimeShift_2 = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.dsbTimeShift_2.setMinimum(-1500.0)
        self.dsbTimeShift_2.setMaximum(1500.0)
        self.dsbTimeShift_2.setObjectName(_fromUtf8("dsbTimeShift_2"))
        self.gridLayout_6.addWidget(self.dsbTimeShift_2, 3, 1, 2, 1)
        self.pbApplyTDManiuplation_2 = QtGui.QPushButton(self.groupBox_6)
        self.pbApplyTDManiuplation_2.setObjectName(_fromUtf8("pbApplyTDManiuplation_2"))
        self.gridLayout_6.addWidget(self.pbApplyTDManiuplation_2, 7, 2, 1, 1)
        self.pbCancelTDManipulation_2 = QtGui.QPushButton(self.groupBox_6)
        self.pbCancelTDManipulation_2.setObjectName(_fromUtf8("pbCancelTDManipulation_2"))
        self.gridLayout_6.addWidget(self.pbCancelTDManipulation_2, 7, 0, 1, 1)
        self.pbTDManipulatePreview_2 = QtGui.QPushButton(self.groupBox_6)
        self.pbTDManipulatePreview_2.setObjectName(_fromUtf8("pbTDManipulatePreview_2"))
        self.gridLayout_6.addWidget(self.pbTDManipulatePreview_2, 7, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(654, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 4, 4, 5, 1)
        self.dsbAmplitudeFactor_2 = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.dsbAmplitudeFactor_2.setDecimals(6)
        self.dsbAmplitudeFactor_2.setMinimum(-9999.0)
        self.dsbAmplitudeFactor_2.setMaximum(9999.0)
        self.dsbAmplitudeFactor_2.setSingleStep(0.01)
        self.dsbAmplitudeFactor_2.setProperty("value", 1.0)
        self.dsbAmplitudeFactor_2.setObjectName(_fromUtf8("dsbAmplitudeFactor_2"))
        self.gridLayout_6.addWidget(self.dsbAmplitudeFactor_2, 2, 1, 1, 1)
        self.cbwhichGraphs_6 = QtGui.QComboBox(self.groupBox_6)
        self.cbwhichGraphs_6.setObjectName(_fromUtf8("cbwhichGraphs_6"))
        self.cbwhichGraphs_6.addItem(_fromUtf8(""))
        self.cbwhichGraphs_6.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cbwhichGraphs_6, 1, 0, 1, 3)
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_6)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 3, 2, 1, 1)
        self.rbManipulateCopy_6 = QtGui.QRadioButton(self.groupBox_6)
        self.rbManipulateCopy_6.setObjectName(_fromUtf8("rbManipulateCopy_6"))
        self.gridLayout_6.addWidget(self.rbManipulateCopy_6, 5, 1, 1, 1)
        self.rbManipulateReplace_6 = QtGui.QRadioButton(self.groupBox_6)
        self.rbManipulateReplace_6.setChecked(True)
        self.rbManipulateReplace_6.setObjectName(_fromUtf8("rbManipulateReplace_6"))
        self.gridLayout_6.addWidget(self.rbManipulateReplace_6, 5, 0, 1, 1)
        self.leNewName_2 = QtGui.QLineEdit(self.groupBox_6)
        self.leNewName_2.setObjectName(_fromUtf8("leNewName_2"))
        self.gridLayout_6.addWidget(self.leNewName_2, 5, 2, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_6)
        self.preferences.addWidget(self.fdmanipulation)
        self.fdmovingaveraging = QtGui.QWidget()
        self.fdmovingaveraging.setObjectName(_fromUtf8("fdmovingaveraging"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.fdmovingaveraging)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.groupBox_8 = QtGui.QGroupBox(self.fdmovingaveraging)
        self.groupBox_8.setEnabled(True)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_19 = QtGui.QLabel(self.groupBox_8)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 1, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_8.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_8)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 1, 2, 1, 1)
        self.rbManipulateCopy_7 = QtGui.QRadioButton(self.groupBox_8)
        self.rbManipulateCopy_7.setObjectName(_fromUtf8("rbManipulateCopy_7"))
        self.gridLayout_8.addWidget(self.rbManipulateCopy_7, 2, 1, 1, 1)
        self.pbCancelTDManipulation_3 = QtGui.QPushButton(self.groupBox_8)
        self.pbCancelTDManipulation_3.setObjectName(_fromUtf8("pbCancelTDManipulation_3"))
        self.gridLayout_8.addWidget(self.pbCancelTDManipulation_3, 3, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(654, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 3, 3, 1, 1)
        self.pbTDManipulatePreview_3 = QtGui.QPushButton(self.groupBox_8)
        self.pbTDManipulatePreview_3.setObjectName(_fromUtf8("pbTDManipulatePreview_3"))
        self.gridLayout_8.addWidget(self.pbTDManipulatePreview_3, 3, 1, 1, 1)
        self.rbManipulateReplace_7 = QtGui.QRadioButton(self.groupBox_8)
        self.rbManipulateReplace_7.setChecked(True)
        self.rbManipulateReplace_7.setObjectName(_fromUtf8("rbManipulateReplace_7"))
        self.gridLayout_8.addWidget(self.rbManipulateReplace_7, 2, 0, 1, 1)
        self.leNewName_4 = QtGui.QLineEdit(self.groupBox_8)
        self.leNewName_4.setObjectName(_fromUtf8("leNewName_4"))
        self.gridLayout_8.addWidget(self.leNewName_4, 2, 2, 1, 1)
        self.pbApplyTDManiuplation_3 = QtGui.QPushButton(self.groupBox_8)
        self.pbApplyTDManiuplation_3.setObjectName(_fromUtf8("pbApplyTDManiuplation_3"))
        self.gridLayout_8.addWidget(self.pbApplyTDManiuplation_3, 3, 2, 1, 1)
        self.cbwhichGraphs_7 = QtGui.QComboBox(self.groupBox_8)
        self.cbwhichGraphs_7.setObjectName(_fromUtf8("cbwhichGraphs_7"))
        self.cbwhichGraphs_7.addItem(_fromUtf8(""))
        self.cbwhichGraphs_7.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cbwhichGraphs_7, 0, 0, 1, 3)
        self.horizontalLayout_10.addWidget(self.groupBox_8)
        self.preferences.addWidget(self.fdmovingaveraging)
        self.fdfiltering = QtGui.QWidget()
        self.fdfiltering.setObjectName(_fromUtf8("fdfiltering"))
        self.preferences.addWidget(self.fdfiltering)
        self.verticalLayout.addWidget(self.preferences)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        TeraView.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(TeraView)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1247, 31))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPlots = QtGui.QMenu(self.menuBar)
        self.menuPlots.setObjectName(_fromUtf8("menuPlots"))
        self.menuSpectrum_Analysis = QtGui.QMenu(self.menuPlots)
        self.menuSpectrum_Analysis.setObjectName(_fromUtf8("menuSpectrum_Analysis"))
        self.menuData_Operations = QtGui.QMenu(self.menuBar)
        self.menuData_Operations.setObjectName(_fromUtf8("menuData_Operations"))
        self.menuTime_Domain = QtGui.QMenu(self.menuData_Operations)
        self.menuTime_Domain.setObjectName(_fromUtf8("menuTime_Domain"))
        TeraView.setMenuBar(self.menuBar)
        self.mainStatus = QtGui.QStatusBar(TeraView)
        self.mainStatus.setSizeGripEnabled(True)
        self.mainStatus.setObjectName(_fromUtf8("mainStatus"))
        TeraView.setStatusBar(self.mainStatus)
        self.toolBar = QtGui.QToolBar(TeraView)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        TeraView.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad = QtGui.QAction(TeraView)
        self.actionLoad.setCheckable(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Pictures/icons/import-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionClose = QtGui.QAction(TeraView)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/ToolbarIcons-full-20101107/png/32/Modern3D/objects/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon1)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionPlot_uncertainty_intervals = QtGui.QAction(TeraView)
        self.actionPlot_uncertainty_intervals.setObjectName(_fromUtf8("actionPlot_uncertainty_intervals"))
        self.actionPlot_SNR = QtGui.QAction(TeraView)
        self.actionPlot_SNR.setObjectName(_fromUtf8("actionPlot_SNR"))
        self.actionPlot_Dynamic_Range = QtGui.QAction(TeraView)
        self.actionPlot_Dynamic_Range.setObjectName(_fromUtf8("actionPlot_Dynamic_Range"))
        self.actionNoise_Floor_calculated = QtGui.QAction(TeraView)
        self.actionNoise_Floor_calculated.setObjectName(_fromUtf8("actionNoise_Floor_calculated"))
        self.actionNoise_Floor_from_fft = QtGui.QAction(TeraView)
        self.actionNoise_Floor_from_fft.setObjectName(_fromUtf8("actionNoise_Floor_from_fft"))
        self.actionFrequency_Domain = QtGui.QAction(TeraView)
        self.actionFrequency_Domain.setObjectName(_fromUtf8("actionFrequency_Domain"))
        self.actionZero_Padding = QtGui.QAction(TeraView)
        self.actionZero_Padding.setObjectName(_fromUtf8("actionZero_Padding"))
        self.actionWindowing = QtGui.QAction(TeraView)
        self.actionWindowing.setObjectName(_fromUtf8("actionWindowing"))
        self.actionScale_Data = QtGui.QAction(TeraView)
        self.actionScale_Data.setObjectName(_fromUtf8("actionScale_Data"))
        self.actionInterpolate_Data = QtGui.QAction(TeraView)
        self.actionInterpolate_Data.setObjectName(_fromUtf8("actionInterpolate_Data"))
        self.actionAverage_Datasets = QtGui.QAction(TeraView)
        self.actionAverage_Datasets.setObjectName(_fromUtf8("actionAverage_Datasets"))
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionClose)
        self.menuSpectrum_Analysis.addAction(self.actionPlot_uncertainty_intervals)
        self.menuSpectrum_Analysis.addAction(self.actionPlot_SNR)
        self.menuSpectrum_Analysis.addAction(self.actionPlot_Dynamic_Range)
        self.menuSpectrum_Analysis.addAction(self.actionNoise_Floor_calculated)
        self.menuSpectrum_Analysis.addAction(self.actionNoise_Floor_from_fft)
        self.menuPlots.addAction(self.menuSpectrum_Analysis.menuAction())
        self.menuTime_Domain.addAction(self.actionZero_Padding)
        self.menuTime_Domain.addAction(self.actionWindowing)
        self.menuTime_Domain.addAction(self.actionScale_Data)
        self.menuTime_Domain.addAction(self.actionInterpolate_Data)
        self.menuTime_Domain.addAction(self.actionAverage_Datasets)
        self.menuData_Operations.addAction(self.menuTime_Domain.menuAction())
        self.menuData_Operations.addAction(self.actionFrequency_Domain)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuPlots.menuAction())
        self.menuBar.addAction(self.menuData_Operations.menuAction())
        self.toolBar.addAction(self.actionLoad)

        self.retranslateUi(TeraView)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TeraView)

    def retranslateUi(self, TeraView):
        TeraView.setWindowTitle(_translate("TeraView", "MainWindow", None))
        self.fileTree.headerItem().setText(0, _translate("TeraView", "Plot", None))
        self.fileTree.headerItem().setText(1, _translate("TeraView", "Name", None))
        self.fileTree.headerItem().setText(2, _translate("TeraView", "Time Domain Info", None))
        self.fileTree.headerItem().setText(3, _translate("TeraView", "Frequency Domain Info", None))
        self.groupBox.setTitle(_translate("TeraView", "Time Domain Manipulation", None))
        self.pbApplyTDManipulation.setText(_translate("TeraView", "Apply", None))
        self.pbCancelTDManipulation.setText(_translate("TeraView", "Cancel", None))
        self.pbPreviewTDManipulation.setText(_translate("TeraView", "Preview", None))
        self.label.setText(_translate("TeraView", "Rescale Amplitude ", None))
        self.label_2.setText(_translate("TeraView", "Shift Time Axis by", None))
        self.label_6.setText(_translate("TeraView", "ps", None))
        self.rbManipulateCopy.setText(_translate("TeraView", "Create a Copy", None))
        self.rbManipulateReplace.setText(_translate("TeraView", "Replace Data", None))
        self.groupBox_2.setTitle(_translate("TeraView", "Time Domain Windowing", None))
        self.pbApplyWindowing.setText(_translate("TeraView", "Apply", None))
        self.pbCancelWindowing.setText(_translate("TeraView", "Cancel", None))
        self.pbPreviewWindowing.setText(_translate("TeraView", "Preview", None))
        self.label_4.setText(_translate("TeraView", "Rising Edge of", None))
        self.label_3.setText(_translate("TeraView", "Choose Window Function", None))
        self.cbwindowfunction.setItemText(0, _translate("TeraView", "Blackman", None))
        self.cbwindowfunction.setItemText(1, _translate("TeraView", "other", None))
        self.label_5.setText(_translate("TeraView", "ps", None))
        self.rbManipulateReplace_windowing.setText(_translate("TeraView", "Replace Data", None))
        self.rbManipulateCopy_windowing.setText(_translate("TeraView", "Copy to ", None))
        self.groupBox_3.setTitle(_translate("TeraView", "Zero Padding", None))
        self.pbApplyPadding.setText(_translate("TeraView", "Apply", None))
        self.pbCancelPadding.setText(_translate("TeraView", "Cancel", None))
        self.pbPreviewPadding.setText(_translate("TeraView", "Preview", None))
        self.label_7.setText(_translate("TeraView", "Number of Zeros", None))
        self.cbZeroPadding.setItemText(0, _translate("TeraView", "after data, plain zero", None))
        self.cbZeroPadding.setItemText(1, _translate("TeraView", "before data, plain zero", None))
        self.cbZeroPadding.setItemText(2, _translate("TeraView", "after data, gaussian", None))
        self.cbZeroPadding.setItemText(3, _translate("TeraView", "before data, gaussian", None))
        self.rbManipulateReplace_Padding.setText(_translate("TeraView", "Replace Data", None))
        self.rbManipulateCopy_Padding.setText(_translate("TeraView", "Copy to ", None))
        self.label_8.setText(_translate("TeraView", "Zero padd", None))
        self.groupBox_4.setTitle(_translate("TeraView", "Interpolation of Time Domain Data", None))
        self.label_11.setText(_translate("TeraView", "fs timestep", None))
        self.pbApplyInterpolation.setText(_translate("TeraView", "Apply", None))
        self.pbCancelInterpolation.setText(_translate("TeraView", "Cancel", None))
        self.pbPreviewInterpolation.setText(_translate("TeraView", "Preview", None))
        self.rbManipulateReplace_interpolation.setText(_translate("TeraView", "Replace Data", None))
        self.rbManipulateCopy_interpolation.setText(_translate("TeraView", "Copy to ", None))
        self.cbwhichGraphs_interpolation.setItemText(0, _translate("TeraView", "Selected", None))
        self.cbwhichGraphs_interpolation.setItemText(1, _translate("TeraView", "All", None))
        self.label_10.setText(_translate("TeraView", "Interpolation to ", None))
        self.groupBox_7.setTitle(_translate("TeraView", "Average Several Datasets", None))
        self.label_16.setText(_translate("TeraView", "Average  in ", None))
        self.pbCancelAveraging.setText(_translate("TeraView", "Cancel", None))
        self.pbApplyAveraging.setText(_translate("TeraView", "Apply", None))
        self.pbPreviewAveraging.setText(_translate("TeraView", "Preview", None))
        self.label_17.setText(_translate("TeraView", "New Name", None))
        self.cbAverageWhere.setItemText(0, _translate("TeraView", "Time Domain", None))
        self.cbAverageWhere.setItemText(1, _translate("TeraView", "Frequency Domain", None))
        self.groupBox_5.setTitle(_translate("TeraView", "Interpolation of Frequency Domain Data", None))
        self.label_12.setText(_translate("TeraView", "GHz Frequency Step", None))
        self.pbApplyInterpolation_2.setText(_translate("TeraView", "Apply", None))
        self.pbCancelInterpolation_2.setText(_translate("TeraView", "Cancel", None))
        self.pbPreviewInterpolation_2.setText(_translate("TeraView", "Preview", None))
        self.rbManipulateReplace_5.setText(_translate("TeraView", "Replace Data", None))
        self.rbManipulateCopy_5.setText(_translate("TeraView", "Copy to ", None))
        self.cbwhichGraphs_5.setItemText(0, _translate("TeraView", "Selected", None))
        self.cbwhichGraphs_5.setItemText(1, _translate("TeraView", "All", None))
        self.label_13.setText(_translate("TeraView", "Interpolation to ", None))
        self.groupBox_6.setTitle(_translate("TeraView", "Frequency Domain Data Manipulation", None))
        self.pbApplyTDManiuplation_2.setText(_translate("TeraView", "Apply", None))
        self.pbCancelTDManipulation_2.setText(_translate("TeraView", "Cancel", None))
        self.pbTDManipulatePreview_2.setText(_translate("TeraView", "Preview", None))
        self.label_9.setText(_translate("TeraView", "Rescale Amplitude ", None))
        self.cbwhichGraphs_6.setItemText(0, _translate("TeraView", "Selected", None))
        self.cbwhichGraphs_6.setItemText(1, _translate("TeraView", "All", None))
        self.label_14.setText(_translate("TeraView", "Change phase slope by ", None))
        self.rbManipulateCopy_6.setText(_translate("TeraView", "Create a Copy", None))
        self.rbManipulateReplace_6.setText(_translate("TeraView", "Replace Data", None))
        self.groupBox_8.setTitle(_translate("TeraView", "Frequency Domain Moving Averaging", None))
        self.label_19.setText(_translate("TeraView", "Moving Average of ", None))
        self.label_22.setText(_translate("TeraView", "Points", None))
        self.rbManipulateCopy_7.setText(_translate("TeraView", "Create a Copy", None))
        self.pbCancelTDManipulation_3.setText(_translate("TeraView", "Cancel", None))
        self.pbTDManipulatePreview_3.setText(_translate("TeraView", "Preview", None))
        self.rbManipulateReplace_7.setText(_translate("TeraView", "Replace Data", None))
        self.pbApplyTDManiuplation_3.setText(_translate("TeraView", "Apply", None))
        self.cbwhichGraphs_7.setItemText(0, _translate("TeraView", "Selected", None))
        self.cbwhichGraphs_7.setItemText(1, _translate("TeraView", "All", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TeraView", "Spectrum Analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TeraView", "Image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("TeraView", "Optical Constants", None))
        self.menuFile.setTitle(_translate("TeraView", "File", None))
        self.menuPlots.setTitle(_translate("TeraView", "Plots", None))
        self.menuSpectrum_Analysis.setTitle(_translate("TeraView", "Spectrum Analysis", None))
        self.menuData_Operations.setTitle(_translate("TeraView", "Data Operations", None))
        self.menuTime_Domain.setTitle(_translate("TeraView", "Time Domain", None))
        self.toolBar.setWindowTitle(_translate("TeraView", "toolBar", None))
        self.actionLoad.setText(_translate("TeraView", "Import", None))
        self.actionClose.setText(_translate("TeraView", "Close", None))
        self.actionPlot_uncertainty_intervals.setText(_translate("TeraView", "plot uncertainty intervals", None))
        self.actionPlot_SNR.setText(_translate("TeraView", "plot SNR", None))
        self.actionPlot_Dynamic_Range.setText(_translate("TeraView", "plot Dynamic Range", None))
        self.actionNoise_Floor_calculated.setText(_translate("TeraView", "Noise Floor calculated", None))
        self.actionNoise_Floor_from_fft.setText(_translate("TeraView", "Noise Floor from fft", None))
        self.actionFrequency_Domain.setText(_translate("TeraView", "Frequency Domain", None))
        self.actionZero_Padding.setText(_translate("TeraView", "Zero Padding", None))
        self.actionWindowing.setText(_translate("TeraView", "Windowing", None))
        self.actionScale_Data.setText(_translate("TeraView", "Modify Data", None))
        self.actionInterpolate_Data.setText(_translate("TeraView", "Interpolate Data", None))
        self.actionAverage_Datasets.setText(_translate("TeraView", "Average Datasets", None))

from matplotlibwidget import MatplotlibWidget
